POST http://localhost:3001/api/patients/
Content-Type: application/json

{
    "name": "Esko Myyrä",
    "dateOfBirth": "1982-07-02",
    "ssn": "020782A9999",
    "gender": "male",
    "occupation": "moviestar"
}